### ISSUE TITLE
Signature of 'update' method is not matched to signature of interface

### ISSUE THREAD

**Issue by NickduD** [ncedu-tlt/2020-ta-cargo#4]
https://github.com/ncedu-tlt/2020-ta-cargo/blob/d57f1c65b0085bce06e29facf460d90d33d7032d/src/main/java/com/netcracker/service/BoxService.java#L38

Сигнатура метода отличается от сигнатуры метода в интерфейсе.
Поправь в соответствии с интерфейсом

**Comment by FriedrichBlack** [comment]
Всё поправил и отправил пул реквест
